[package]
name = "graphgate"
version = "0.5.1"
authors = ["Sunli <scott_s829@163.com>"]
edition = "2018"
description = "GraphGate is Apollo Federation implemented in Rust"
license = "MIT/Apache-2.0"
homepage = "https://github.com/async-graphql/graphgate"
repository = "https://github.com/async-graphql/graphgate"
keywords = ["gateway", "graphql", "federation"]
readme = "README.md"

[dependencies]
graphgate-handler = { version = "0.5.0", path = "./crates/handler" }

serde = { version = "1.0.125", features = ["derive"] }
anyhow = "1.0.39"
structopt = "0.3.21"
kube = { version = "0.51.0", features = ["derive", "native-tls"], default-features = false }
k8s-openapi = { version = "0.11.0", features = ["v1_19"], default-features = false }
tokio = { version = "1.4.0", features = ["rt-multi-thread", "time", "macros", "sync", "signal"] }
warp = { version = "0.3.0", features = ["compression"] }
toml = "0.5.8"
futures-util = "0.3.13"
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
opentelemetry = { version = "0.13.0", features = ["rt-tokio", "metrics"] }
opentelemetry-jaeger = "0.12.0"
opentelemetry-prometheus = "0.6.0"
prometheus = "0.12.0"

[dev-dependencies]
async-graphql = { version = "2.8.3", features = ["apollo_tracing"] }
async-graphql-warp = "2.8.3"
fastrand = "1.4.0"
async-stream = "0.3.0"
futures-util = "0.3.13"

[[example]]
name = "builtin_scalar_bug"
path = "./examples/builtin_scalar_bug/bug.rs"

[workspace]
members = [
    "crates/schema",
    "crates/planner",
    "crates/validation",
    "crates/handler",
]
